### ISSUE TITLE
N-gram model does not exist

### ISSUE THREAD

**Issue by demdecuong** [iotayo/aivivn-tone#2]
[https://drive.google.com/file/d/14RmQSYgijeSVzZNZ2mPGL0lCLg_guXGE/view?usp=sharing](url)

**Comment by iotayo** [comment]
Hi demdecuong,

The 4-gram language model is too large to keep in my personal Google Drive, so I pulled it out 3 months after my submission.

Please consider building one yourself, using the CSV V2 data from this repo https://github.com/binhvq/news-corpus, and follow the instructions from kenlm's website https://kheafield.com/code/kenlm/estimation/

Thank you for your understanding.
