### ISSUE TITLE
checkpoint/aivivn_tone.model.ep25 not found

### ISSUE THREAD

**Issue by cuongnguyengit** [iotayo/aivivn-tone#3]
Hi,

Can you give me the model checkpoint submitted in the aivivn contest?
I need to run predict code, i am a beginer in the issue.

Thanks

**Comment by iotayo** [comment]
Hello,

The link for the checkpoint is available in the README:
https://github.com/iotayo/aivivn-tone#replicating-submission-results

For the seq2seq model: https://drive.google.com/file/d/1cWp0P2Uj6rcXZzqpfQt9kY8a9SlLEsNU/view

For the n-gram model, you will need to build it yourself, as I ran out of GDrive space a while ago. Please check out this issue https://github.com/iotayo/aivivn-tone/issues/2.

Thank you.
