### ISSUE TITLE
Resume Checkpoint Error while saving model

### ISSUE THREAD

**Issue by cuongnguyengit** [iotayo/aivivn-tone#4]
Hi,

I tried to resume your checkpoint with my data. Specifically, My code is 
 trainer.resume_in_parts(train_parts, val, val_iterator, batch_size,save_path="./aivivn_tone.model.ep25")

Then i had a error that likes:

Total parameters: 16995327
Training part [data/train.txt] with target [data/train.txt]...
epoch = 26  iter = 0  loss = 0.433  correct = 92.504  r_correct = 94.407  c_correct = 95.789
EPOCH = 26  AVG_LOSS = 0.259  AVG_CORRECT = 86.402

Traceback (most recent call last):
  File "train.py", line 347, in <module>
    trainer.resume_in_parts(train_parts, val, val_iterator, batch_size, save_path="./aivivn_tone.model.ep25")
  File "train.py", line 138, in resume_in_parts
    self.train_in_parts(train_parts, val, val_iterator, batch_size, start_epoch=start_epoch)
  File "train.py", line 114, in train_in_parts
    self.save(epoch)
  File "train.py", line 242, in save
    }, os.path.join(save_path, "aivivn_tone.model.ep{}".format(epoch)))
  File "//python3.7/site-packages/torch/serialization.py", line 372, in save
    _save(obj, opened_zipfile, pickle_module, pickle_protocol)
  File "/python3.7/site-packages/torch/serialization.py", line 476, in _save
    pickler.dump(obj)
  File "/python3.7/site-packages/torch/optim/optimizer.py", line 59, in __getstate__
    'defaults': self.defaults,
AttributeError: 'Adam' object has no attribute 'defaults'

Can you help me fix the issue?

Thanks you.

**Comment by attrn** [comment]
Hello,

This is a little bit difficult for me to debug. 

Are you sure you're running my original code? For example, I don't think my train.py code has line 347.

Also, PyTorch definitions change a lot between versions. Please try to create an environment with PyTorch 1.0.1 and run again.

Thank you.

**Comment by iotayo** [comment]
Hello,

This is a little bit difficult for me to debug.

Are you certain you're running my original code? For example, I don't think my train.py code has line 347.

Also, what version of PyTorch are you using? PyTorch definitions change a lot between versions. Please try to create an environment with PyTorch 1.0.1 and run again.

Thank you.

**Comment by cuongnguyengit** [comment]
It work for me. 

Thank you.
