### ISSUE TITLE
Language model

### ISSUE THREAD

**Issue by CuongNN218** [iotayo/aivivn-tone#5]
Chào bạn, mình đang tìm hiểu về kenLM, mô hình của bạn trên drive không còn download được nữa, bạn có thể cập nhật lại link giúp mình được không @iotayo 
Mình cảm ơn

**Comment by iotayo** [comment]
Hi bạn,

Do drive của mình không đủ chỗ để lưu model nên mình đã gỡ cách đây 1 thời gian.

Bạn có thể tự download dữ liệu từ https://github.com/binhvq/news-corpus
và chạy các lệnh theo hướng dẫn của tác giả KenLM: https://kheafield.com/code/kenlm/estimation/

KenLM chỉ dùng CPU và chạy khá nhanh nên bạn có thể dựng model của riêng mình khá dễ dàng.
Mong bạn thông cảm.

**Comment by CuongNN218** [comment]
Cảm ơn bạn đã trả lời khá nhanh. Mình muốn hỏi thêm 1 chút.
@iotayo không biết bạn dùng bộ corpus nào nhỉ bản v2 full text giải nén 27gb đúng k nhỉ ?

**Comment by iotayo** [comment]
đúng vậy đó bạn

**Comment by CuongNN218** [comment]
https://github.com/iotayo/aivivn-tone/blob/7f3d5ce41d5a0bd659f3aaeb7d351a7a046c3004/predict.py#L178
@iotayo  mình vẫn chưa hiểu rõ cách dùng KenLM để tính ra score, thông thường theo beamsearch thì score sau = score_topk_trước + score hiện tại (sau log_softmax), vậy khi dùng KenLM thì score sẽ được tính toán như thế nào?

**Comment by iotayo** [comment]
https://github.com/iotayo/aivivn-tone/blob/7f3d5ce41d5a0bd659f3aaeb7d351a7a046c3004/predict.py#L146-L151

Mình có giải thích ở phần comment, nhưng có thể chưa được rõ ràng lắm.

Khi bắt đầu mỗi vòng lặp khi beam search thì mình có 1 số biến là:

`left_contexts`: là 1 list gồm top-k `left_context` từ vòng lặp trước đó
`c`: kí tự đang cần được search ở vòng lặp này
`c_list`: là 1 list gồm các kí tự có dấu tương ứng với `c` (ví dụ nếu `c` là 'a' thì `c_list` là [a, á, ạ, ã, ...])
`right_context`: substring ở bên phải `c`

`candidate` = `left_contexts` + `c` + `right_context`

Như vậy sẽ có tất cả `len(left_contexts)` x `len(c_list)` candidates.

Mình score tất cả các candidates này bằng KenLM, rồi chọn ra top-k, và lưu vào `left_contexts` để sử dụng cho vòng lặp tiếp theo.

**Comment by CuongNN218** [comment]
@iotayo Mình muốn hỏi thêm 1 chút, các candidates của bạn ở đây là ở dạng gì ? n-gram character level hay chỉ là characters ?
Hiện tại mình đã dựng 1 3-gram character-level model với kenlm. Mục tiêu của mình là dùng nó để rescoring cho 1 seq2seq decoder với beamsearch. Thông thường mình sẽ dùng top_k_score của step trước + score của step này để tính ra score cho từng step beamsearch. nếu mình muốn dùng thêm 3-gram kenlm thì mình nên làm như thế nào. Mong bạn giải đáp.

**Comment by iotayo** [comment]
Hàm `score` của kenlm nhận vào 1 space-delimited string (vd, `model.score('this is a sentence .')`), nên candidates của mình được xử lí để chuyển sang dạng này trước khi score.

Nếu bạn muốn sử dụng n-gram character level model thì bạn phải split lại string trước khi dùng hàm `score` của kenlm (vd, `model.score('t h i s  i s  a  s e n t e n c e  .')`)

Ở mỗi step bạn lưu lại top-k của step hiện tại để sử dụng cho step tiếp theo; mình nghĩ như vậy khá hợp lí.
